name: Obe
main: me.myeolchi.obe.ObePlugin
version: 1.0.0
api-version: 1.19
libraries:
  - io.github.monun:tap-core:4.8.0
  - io.github.monun:heartbeat-coroutines:0.0.4
  - io.github.monun:kommand-core:2.14.0